sonar.projectKey=CTSE-PropertyHub_propertyhub-tenancy-service
sonar.organization=ctse-propertyhub
sonar.sources=src
sonar.exclusions=node_modules/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
